### ISSUE TITLE
有一些chia的交易问题

### ISSUE THREAD

**Issue by yaoyf888** [chuwt/chia-bls-go#1]
1、如何组成一个转账交易

**Comment by chuwt** [comment]
@yaoyf888 目前可以通过调用节点rpc发起转账，最近太忙，还没时间做go的交易离线签名。
目前了解到的一些信息是，需要先将public_key转成puzzle_hash，然后转成xch开头的地址，这一步是通过clvm处理的。
交易的离线签名好像也会涉及到clvm处理。

**Comment by yaoyf888** [comment]
@chuwt 是的，我也发现很多东西都需要CLVM处理，这块是不是只能通过python处理

**Comment by chuwt** [comment]
@yaoyf888 嗯嗯，是的，如果用go处理的话需要实现clvm，这样工作量就太大了。所以我打算直接抽离封装交易的python代码做成rpc服务，获取封装的数据之后再用签名发送

**Comment by yaoyf888** [comment]
@chuwt 我现在就在做chia的离线交易，封装交易这块卡了很久了，没办法只能把这块python代码提取出来做成个接口，我去调用，然后再用你的签名对数据进行签名，再用push_tx推出去，目前是这样个思路，不知道可不可行

**Comment by chuwt** [comment]
@yaoyf888 思路可以的，不过需要修改下chia封装交易的那块代码

**Comment by yaoyf888** [comment]
@chuwt 是的，有点头大，有不少地方需要改动下，你对python熟悉吗？

**Comment by chuwt** [comment]
@yaoyf888 嗯嗯，我是python+go，有兴趣可以一起搞一下

**Comment by yaoyf888** [comment]
@chuwt 可以呀，方便加个微信啥的，一起搞一下

**Comment by chuwt** [comment]
@yaoyf888 MTg2MTI1Mzc1NjE=

**Comment by yaoyf888** [comment]
@chuwt 没找到这个号啊，需要解码下？

**Comment by chuwt** [comment]
@yaoyf888 额，是的，base64 decode一下
